# Generated by Django 5.1.3 on 2024-11-07 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlib_api', '0002_book_category_alter_reader_reader_rank_copy_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
