# Generated by Django 5.1.3 on 2024-11-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlib_api', '0003_book_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_reading_counter',
            field=models.IntegerField(default=0),
        ),
    ]
