# Generated by Django 5.1.3 on 2024-11-08 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlib_api', '0004_book_book_reading_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_rating_avg',
            field=models.IntegerField(default=0),
        ),
    ]
