# Generated by Django 5.1.3 on 2024-11-08 20:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlib_api', '0005_book_book_rating_avg'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_uploaded_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='gamification_record',
            name='date_and_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
