# Generated by Django 5.1.3 on 2024-11-08 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlib_api', '0006_book_book_uploaded_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copy_book',
            name='book',
            field=models.ForeignKey(db_column='book_id', on_delete=django.db.models.deletion.CASCADE, to='smartlib_api.book'),
        ),
        migrations.AlterField(
            model_name='copy_book',
            name='reader',
            field=models.ForeignKey(db_column='reader_id', on_delete=django.db.models.deletion.CASCADE, to='smartlib_api.reader'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='reader',
            field=models.ForeignKey(db_column='reader_id', on_delete=django.db.models.deletion.CASCADE, to='smartlib_api.reader'),
        ),
        migrations.AlterField(
            model_name='gamification_record',
            name='reader',
            field=models.ForeignKey(db_column='reader_id', on_delete=django.db.models.deletion.CASCADE, to='smartlib_api.reader'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='smartlib_api.user'),
        ),
        migrations.AlterField(
            model_name='note',
            name='copy_book',
            field=models.ForeignKey(db_column='copy_book_id', on_delete=django.db.models.deletion.CASCADE, to='smartlib_api.copy_book'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='manager',
            field=models.ForeignKey(db_column='manager_id', on_delete=django.db.models.deletion.CASCADE, to='smartlib_api.manager'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='reader',
            field=models.ForeignKey(db_column='reader_id', on_delete=django.db.models.deletion.CASCADE, to='smartlib_api.reader'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='category',
            field=models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, to='smartlib_api.category'),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='reader',
            field=models.ForeignKey(db_column='reader_id', on_delete=django.db.models.deletion.CASCADE, to='smartlib_api.reader'),
        ),
        migrations.AlterField(
            model_name='rating_and_review',
            name='book',
            field=models.ForeignKey(db_column='book_id', on_delete=django.db.models.deletion.CASCADE, to='smartlib_api.book'),
        ),
        migrations.AlterField(
            model_name='rating_and_review',
            name='reader',
            field=models.ForeignKey(db_column='reader_id', on_delete=django.db.models.deletion.CASCADE, to='smartlib_api.reader'),
        ),
        migrations.AlterField(
            model_name='search',
            name='reader',
            field=models.ForeignKey(db_column='reader_id', on_delete=django.db.models.deletion.CASCADE, to='smartlib_api.reader'),
        ),
        migrations.AlterUniqueTogether(
            name='copy_book',
            unique_together={('copy_book_id', 'book', 'reader')},
        ),
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together={('feedback_id', 'reader')},
        ),
        migrations.AlterUniqueTogether(
            name='gamification_record',
            unique_together={('gamification_record_id', 'reader')},
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('note_id', 'copy_book')},
        ),
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together={('notification_id', 'reader', 'manager')},
        ),
        migrations.AlterUniqueTogether(
            name='preferences',
            unique_together={('preferences_id', 'reader', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='rating_and_review',
            unique_together={('rating_and_review_id', 'book', 'reader')},
        ),
        migrations.AlterUniqueTogether(
            name='search',
            unique_together={('search_id', 'reader')},
        ),
    ]
