# Generated by Django 5.1.3 on 2024-11-12 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlib_api', '0007_alter_copy_book_book_alter_copy_book_reader_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='favourite_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('wish_list_id', models.AutoField(primary_key=True, serialize=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartlib_api.book')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartlib_api.reader')),
            ],
            options={
                'db_table': 'Wish_List',
                'unique_together': {('wish_list_id', 'book', 'reader')},
            },
        ),
    ]
