# Generated by Django 5.1.3 on 2024-11-12 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartlib_api', '0008_book_favourite_counter_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='favourite_counter',
            new_name='book_favourite_counter',
        ),
    ]
