# Generated by Django 5.1.3 on 2024-11-12 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlib_api', '0009_rename_favourite_counter_book_book_favourite_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(db_column='category_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='smartlib_api.category'),
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('book_id', 'category')},
        ),
    ]
