# Generated by Django 5.1.3 on 2024-11-13 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlib_api', '0010_book_category_alter_book_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='book',
            field=models.ForeignKey(db_column='book_id', on_delete=django.db.models.deletion.CASCADE, to='smartlib_api.book'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='reader',
            field=models.ForeignKey(db_column='reader_id', on_delete=django.db.models.deletion.CASCADE, to='smartlib_api.reader'),
        ),
        migrations.CreateModel(
            name='BookContinueReading',
            fields=[
                ('continue_reading_id', models.AutoField(primary_key=True, serialize=False)),
                ('book', models.ForeignKey(db_column='book_id', on_delete=django.db.models.deletion.CASCADE, to='smartlib_api.book')),
                ('reader', models.ForeignKey(db_column='reader_id', on_delete=django.db.models.deletion.CASCADE, to='smartlib_api.reader')),
            ],
            options={
                'db_table': 'Book_Continue_Reading',
                'unique_together': {('continue_reading_id', 'book', 'reader')},
            },
        ),
    ]
