# Generated by Django 5.1.3 on 2024-11-13 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlib_api', '0011_alter_wishlist_book_alter_wishlist_reader_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedBook',
            fields=[
                ('uploaded_book_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('book', models.ForeignKey(db_column='book_id', on_delete=django.db.models.deletion.CASCADE, to='smartlib_api.book')),
                ('reader', models.ForeignKey(db_column='reader_id', on_delete=django.db.models.deletion.CASCADE, to='smartlib_api.reader')),
            ],
            options={
                'db_table': 'Uploaded_Book',
                'unique_together': {('uploaded_book_id', 'book', 'reader')},
            },
        ),
    ]
