# Generated by Django 5.1.3 on 2024-11-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlib_api', '0013_remove_uploadedbook_status_book_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_description',
            field=models.CharField(default='No Description', max_length=255),
        ),
    ]
