# Generated by Django 5.1.3 on 2025-01-06 20:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlib_api', '0017_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='feedback_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_title',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='reader',
            name='reader_rank',
            field=models.CharField(default='Rookie', max_length=20),
        ),
    ]
