# Generated by Django 5.1.3 on 2025-02-10 22:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartlib_api', '0018_feedback_feedback_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_file',
            field=models.FileField(blank=True, null=True, upload_to='books/files/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_image',
            field=models.FileField(blank=True, null=True, upload_to='books/images/'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='is_first_time',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
