from django.urls import path
from .views import *




urlpatterns = [
    path('', guestPage, name='guestPage'),
    path('aboutUs', aboutUsPage, name='aboutUsPage'),
    path('privacyPolicy', privacyPolicyPage, name='privacyPolicyPage'),
    path('login', loginPage, name='loginPage'),
    path('registerAccount', registerPage, name='registerPage'), 
    path('confirm_email_register/', confirm_email_register, name='confirm_email_register'), 
    path('send_another_email/<str:email>/', send_another_email, name='send_another_email'),
    path('activate/<uidb64>/<token>/', activate_register.as_view(), name='activate'),
    path('find_account/', findAccountPage, name='findAccountPage'), 
    path('confirm_email_change_password/', confirm_email_change_password, name='confirm_email_change_password'), 
    path('send_another_email_change_pass/<str:email>/', send_another_email_change_pass, name='send_another_email_change_pass'),
    path('activate_change_password/<uidb64>/<token>/', activate_change_password.as_view(), name='activate_change_password'),
    path('resetPasswordPage/<str:email>/', resetPasswordPage, name='resetPasswordPage'),
    path('preferencesPage', preferencesPage, name='preferencesPage'), 
    path('simulationPage', SimulationPage, name='simulationPage'), 
    path('save_preferences/', save_preferences, name='save_preferences'),
    path('user_preferences/<int:user_id>/', UserPreferencesView.as_view(), name='user_preferences'),
    path('update_isFirstTime', UpdateReaderIsFirstTime.as_view(), name='update_isFirstTime'), 
    path('homePage', homePage, name='homePage'), 
    path('rankPage', RankPage, name='rankPage'),
    path('wish-listPage', WishListPage, name='wish-listPage'), 
    path('notificationPage', NotificationPage, name='notificationPage'), 
    path('myUploadedBookPage', MyUploadedBookPage, name='myUploadedBookPage'), 
    path('accountSettingsPage', AccountSettingsPage, name='accountSettingsPage'), 
    path('remove_uploaded_book/', RemoveUploadedBookView.as_view(), name='remove_uploaded_book'),
    path('viewBookPage/<int:book_id>/', ViewBookPage, name='ViewBookPage'),
    path('OpenBookPage/<int:book_id>/', OpenBookPage, name='OpenBookPage'),
    path('login-api', UserLoginView.as_view()),
    path('refresh-token-api', RefreshTokenView.as_view()),
    path('change-password-api', UserChangePasswordView.as_view()),
    path('delete-user-api', DeleteUser.as_view()), 
    path('get_username/<int:user_id>/', UserNameListView.as_view(), name='get_username'),
    path('get_reader_info/', ReaderInfoListView.as_view(), name='get_reader_info'),
    path('get_book_info/', BookInfoListView.as_view(), name='get_book_info'),
    path('creare-continue-reading/', ContinueReadingView.as_view(), name='creare-continue-reading'),
    path('get_uploadedby/', UploadedByView.as_view(), name='get_uploadedby'),
    path('register-api',RegisterAPIView.as_view()),
    path('check-email-api',EmailExistView.as_view()),
    path('reset-password-api', reset_password.as_view()), 
    path('getAllCategories/', CategoryListView.as_view()),
    path('guest-search-page/', GuestSearchPage, name='guest-search'), 
    path('search-page/', ReaderSearchPage, name='reader-search'), 
    path('getAllBooks/', BookListView.as_view()),
    path('add-to-wishlist/', AddBookToWishlist.as_view(), name='add_to_wishlist'),
    path('remove-from-wishlist/', RemoveBookFromWishlist.as_view(), name='remove_from_wishlist'),
    path('check-book-in-wishlist/', CheckBookInWishlist.as_view(), name='check_book_in_wishlist'),
    path('getMostReadedBook/', MostReaded_BookListView.as_view()),
    path('getMostRatingBook/', MostRating_BookListView.as_view()),
    path('getLastUploadedBook/', LastUploaded_BookListView.as_view()),
    path('insertRatingAndReview/', AddRatingAndReviewView.as_view()),
    path('list_Three-rating_and_review/', RatingAndReviewListView.as_view()),
    path('search/', BookSearchView.as_view()),
    path('getMostReadedPreferencesBook/', MostReadedPreferences_BookListView.as_view()),
    path('getMostRatingPreferencesBook/', MostRatingPreferences_BookListView.as_view()),
    path('getLastPreferencesUploadedBook/', LastUploadedPreferences_BookListView.as_view()),
    path('getContinue-reading-books/', BookContinueReadingListView.as_view()),
    path('getGamificationRecord/', GamificationRecordListView.as_view()),
    path('getLastThreeWishListView/', LastThreeWishListView.as_view()),
    path('getLastThreeNotificationListView/', LastThreeNotificationListView.as_view()),
    path('getWishList_ListView/', WishListListView.as_view()),
    path('getNotificationListView/', NotificationListView.as_view()),
    path('InsertFeedbackView/', InsertFeedbackView.as_view()),
    path('getUploadedBookListView/', UploadedBookListView.as_view()),
    path('insertBook/', CreateBookView.as_view()),
    path('insertNewBook/', add_book, name='add_book'),
    path('summarize/', summarize_text, name='summarize_text'),
    path('translate/', translate_text, name='translate_text'),
    path('text_to_speech/', text_to_speech, name='text_to_speech'),
    path('stop_text_to_speech/', stop_text_to_speech, name='stop_text_to_speech'),
]
